// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqzvG8iSEvE44Neav8TQuW4YVpYvbJFck',
    appId: '1:974228484978:web:d90dead1b2642e6e9263eb',
    messagingSenderId: '974228484978',
    projectId: 'medicheck-b9455',
    authDomain: 'medicheck-b9455.firebaseapp.com',
    storageBucket: 'medicheck-b9455.firebasestorage.app',
    measurementId: 'G-3JFP7SRY30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxzhMeON2OYfQwExYDlT06dZimhgTvRec',
    appId: '1:974228484978:android:6da0b05a7fc7dceb9263eb',
    messagingSenderId: '974228484978',
    projectId: 'medicheck-b9455',
    storageBucket: 'medicheck-b9455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIqTLYGpBRJiFUZMWpTOs-_6EXGZMCieo',
    appId: '1:974228484978:ios:d130a1ab18952dda9263eb',
    messagingSenderId: '974228484978',
    projectId: 'medicheck-b9455',
    storageBucket: 'medicheck-b9455.firebasestorage.app',
    iosClientId: '974228484978-rnu2pt54kvjpagik5c9812l88udefb34.apps.googleusercontent.com',
    iosBundleId: 'com.example.phapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIqTLYGpBRJiFUZMWpTOs-_6EXGZMCieo',
    appId: '1:974228484978:ios:d130a1ab18952dda9263eb',
    messagingSenderId: '974228484978',
    projectId: 'medicheck-b9455',
    storageBucket: 'medicheck-b9455.firebasestorage.app',
    iosClientId: '974228484978-rnu2pt54kvjpagik5c9812l88udefb34.apps.googleusercontent.com',
    iosBundleId: 'com.example.phapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqzvG8iSEvE44Neav8TQuW4YVpYvbJFck',
    appId: '1:974228484978:web:8d5cace0de09c0fc9263eb',
    messagingSenderId: '974228484978',
    projectId: 'medicheck-b9455',
    authDomain: 'medicheck-b9455.firebaseapp.com',
    storageBucket: 'medicheck-b9455.firebasestorage.app',
    measurementId: 'G-EF2PVBV4N5',
  );

}